### ISSUE TITLE
Error: Funciones pueden acceder a la tabla de símbolos de la función que las llama.

### ISSUE THREAD

**Issue by javierjaureguij** [ericknavarro/CompiladoresEjercicio3#13]
**Descripción:**

Al ejecutar una entrada como la siguiente:

`Function Void main() {`

`	Declare Number perteneceAMain;`
`	perteneceAMain = 10;`
`	funcion1();	`

`}`
`Function Void funcion1() {`

`	Print("Valor: " & perteneceAMain);	// Debería dar error`

`}`

se debería de producir un error debido a que la variable **perteneceAMain** no existe en el ámbito de la función **funcion1()**, sin embargo se obtiene como resultado el valor de la variable definida en **main**:

![image](https://user-images.githubusercontent.com/45080646/51812445-2644b380-2277-11e9-832a-35c1f70f6a3d.png)

**Solución propuesta:**

El error ocurre debido a que al inicio del método **ejecutar** de la clase **Function**, se crea una tabla de simbolos local con TODAS las referencias las variables pertenecientes a la tabla de simbolos anterior a la llamada al método ejecutar. Esta tabla de símbolos está representada por el parámetro **ts** tal y como se ve a continuación:

![image](https://user-images.githubusercontent.com/45080646/51813053-f5b24900-2279-11e9-9984-794c3ea59f5e.png)

Sin embargo, esto es erróneo en el caso de llamadas a funciones, debido a que la tabla de símbolos local, únicamente se debería inicializar con las referencias a las variables globales y con los valores enviados por medio de los parámetros. Para solucionar este problema, se realizaron las siguientes modificaciones:

1. Se implementó una tabla de símbolos global, cuya referencia se crea al inicio de la ejecución del árbol y cualquier subinstrucción puede acceder a ésta: #12 

2. Se agregó el método **setTablaDeSimbolosPadre** a la clase **Asignacion** para los casos en los que sea necesario pasar valores de la tabla de simbolos padre a la tabla de simbolos local, como lo es al momento de pasar parámetros a una función: #14 

3. Se modificó el método **ejecutar** de la clase **Function** con la implementación de los puntos anteriores: #15 

**Resultado:**

Después de implementada la solución anterior, se obtiene el resultado esperado al ejecutar la entrada descrita la inicio:

![image](https://user-images.githubusercontent.com/45080646/51813417-d2889900-227b-11e9-8c11-24e3ddee4d17.png)

Carné: 201503748

**Comment by ericknavarro** [comment]
Muchas gracias por la solución desarrollada para este problema y por el nivel de detalle en la descripción del mismo.
