### ISSUE TITLE
Error al declarar arreglos

### ISSUE THREAD

**Issue by deahtom123** [ericknavarro/CompiladoresEjercicio3#2]
Al momento de declarar un arreglo no se toma en cuenta que las dimensiones deben de ser numeros.
Para arreglar este problema se utiliza la clase DeclaracionArreglo.java y se deben de agregar las siguientes lineas en la funcion ejecutar antes de agregarlo a la lista enlazada tamaniosDimensiones:
//Se debe de verificar que la variable exista y se le haya dado un valor
if(er == null) {
System.err.println("Una de las dimensiones para la creacion del arreglo es nula");
return null;
}
//Se comprueba que el tipo de la variable sea number
if(!(er instanceof Double)){
System.err.println("Una de las dimensiones para la creacion del arreglo no es numerica");
return null;
}
Carnet: 201504200

**Comment by ericknavarro** [comment]
Se cierra este issue, resuelto en: https://github.com/ericknavarro/CompiladoresEjercicio3/commit/05d0ed72bff0f24b314fd049186c1473dca585f0
