### ISSUE TITLE
Validación de break en ciclos y mensajes de retorno en funciones

### ISSUE THREAD

**Issue by PvasquezF** [ericknavarro/CompiladoresEjercicio3#27]
- De momento no se valida que el break este contenido en un ciclo ya que si se coloca algo como lo siguiente

      function number prueba(){
         break;
      }
    No detecta el error del break, aunque si muestra el siguiente error
       **Una función de tipo Void no puede retornar valores, solamente puede retornar vacío.**

- También cuando queremos retornar en una función  y solo ponemos return 

      function number prueba(){
         return; // debería arrojar un error mencionando que el retorno necesita un valor
      }

     Por el momento arroja este error
     **Una función de tipo Number no puede retornar un valor que no sea numérico.**

- Por ultimo cuando tenemos varias opciones para salir de una función es posible necesitar mas de un retorno por lo tanto

      function number prueba(){
         if(3 < 5){
             return 3; // si se cumple la condición no habría problema, pero si no cumple no retorna
                      // por lo tanto seria un error, ya que necesita de otro return fuera del if
         }
      }

[Revisar merge request #28](https://github.com/ericknavarro/CompiladoresEjercicio3/pull/28)

**Comment by ericknavarro** [comment]
El issue fue corregido con la [propuesta de Pavel](https://github.com/ericknavarro/CompiladoresEjercicio3/pull/28).
