### ISSUE TITLE
Declaración con asignación, asignación entre arreglos, asignación de valores de tipo distinto en los arreglos

### ISSUE THREAD

**Issue by PvasquezF** [ericknavarro/CompiladoresEjercicio3#29]
1. Actualmente no se cuenta con la declaración y asignación al mismo tiempo
ej.
     
       Declare number a = 4; //Esto no es admitido sintácticamente
2. Además tampoco es permitido asignar a un arreglo el valor de otro arreglo
ej.

       declare number a[3][2];
       declare number b[3][2];
       a = b; // causa error debido a que cuando se validan los tipos no está contemplado 
              // la opción de que venga el tipo array solo string, number, boolean
              // el tipo para el arreglo cuando llega a ese punto es *NodoArreglo*

       a[0] = "hola"; // Esto debería ser error ya que se declaro un arreglo number no de string
                          // de momento es valido hacerlo

3. Retorno de arreglo sin valores asignados
ej.

      declare number a[3][2];
      return a[0][0];

al no asignarle valor a esa posición es nulo por lo tanto debería retornar nulo, pero al validar tipos arroja un error.

[`Revisar pull request 30`](https://github.com/ericknavarro/CompiladoresEjercicio3/pull/30)

**Comment by ericknavarro** [comment]
Buenas tardes Pavel, 

Espero te encuentres muy bien, agradezco mucho tus aportes, estos enriquecen mucho nuestro ejemplo, ¿podrías hacer un pull request por cada uno de los elementos reportados en el issue?

- Pull Request 1: Corrección a "Actualmente no se cuenta con la declaración y asignación al mismo tiempo"
- Pull Request 2: Corrección a "Además tampoco es permitido asignar a un arreglo el valor de otro arreglo"
- Pull Request 3: Corrección a "Retorno de arreglo sin valores asignados"

De antemano muchas gracias por tu apoyo.

Saludos cordiales.
