### ISSUE TITLE
Aumento, decremento, Error en Arreglos (asignación de valor)

### ISSUE THREAD

**Issue by JavierHevia** [ericknavarro/CompiladoresEjercicio3#3]
- No efectúa a++; ni a--; por ejemplo.

- Los arreglos si los declaro de esta forma: Declare Number t[2][2]; 
   luego ingreso algún dato en esa posición t[2][2]=3;
   luego lo imprimo: Print("Arreglo " & t[2][2]);
  ERROR: El acceso al arreglo t no puede realizarse porque uno o más de los indices exceden los límites 
  del arreglo.

Solución:  Print("Arreglo " & t[1][1]); si sale el resultado 3. pero como comienza en 0.

Carnet: 201313898

**Comment by ericknavarro** [comment]
++ y -- no estaban definidos como parte del lenguaje
los indices en arreglos comienzan en 0

Por favor leer la definición del lenguaje.
