### ISSUE TITLE
Sobrecarga de Funciones | 200815284

### ISSUE THREAD

**Issue by rjanixz** [ericknavarro/CompiladoresEjercicio3#9]
Actualmente la ejecución falla al tener dos funciones con el mismo nombre y diferente número de parametros. Por ejemplo:

`Function Void Contar(Number hasta) { ... }`
`Function Void Contar(Number desde, Number hasta) { ... }`

debido a que las funciones utilizan únicamente su nombre como Identificaro Único.

Al momento de hacer las llamadas como por ejemplo:

`Contar(4);`
`Contar(2, 4);`

El segundo metodo dará como resultado el error:

![image](https://user-images.githubusercontent.com/6462555/51807791-4a8d9980-2251-11e9-8af7-6d8eb2206a8d.png)

**Solución**
Se extiende la funcionalidad del Identificador Único con los números de parámetros en el siguiente 
PR: https://github.com/ericknavarro/CompiladoresEjercicio3/pull/20

La idea esque las funciones tengan un ID de la forma

- _nombre()  //sin parametros
- _nombre(_tipo_tipo_tipo) // función con 3 parámetros
- _nombre(_tipo) /// función con 1 parámetro

Para esto se agrea al ID el tipo de los parámetros
Una vez extendida la funcionalidad la misma ejecución producirá el resultado esperado:

![image](https://user-images.githubusercontent.com/6462555/51948932-0e446f80-23f0-11e9-861b-340cd8da8758.png)

**Carnet: 200815284**

**Comment by ericknavarro** [comment]
El issue fue resuelto: 
https://github.com/ericknavarro/CompiladoresEjercicio3/pull/20

Se cierra.
